on: [push, pull_request]
name: Test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Go fmt
      run: |
        unformatted=$(gofmt -l .)
        if [ ! -z "$unformatted" ]; then
          echo This files is not formatted $unformatted
          exit 1
        fi
    - name: Go report card
      run: curl -X POST -F "repo=github.com/axpira/goplogadapter" https://goreportcard.com/checks
